export const regularVerbs = ['abandonar', 'degustar', 'meditar', 'dejar', 'mejorar', 'abonar', 'mencionar',
  'abordar', 'depender', 'meter', 'mezclar', 'abrochar', 'depositar', 'migrar',
  'mirar', 'derribar', 'acabar', 'acampar', 'desarrollar', 'molestar', 'acariciar',
  'desatar', 'montar', 'acceder', 'desayunar', 'motivar', 'acelerar', 'descansar', 'mudar',
  'aceptar', 'murmurar', 'aclarar', 'desconectar', 'acomodar', 'descongelar', 'nadar', 'acompañar',
  'descubrir', 'narrar', 'aconsejar', 'desear', 'narrar', 'acoplar', 'necesitar', 'acortar',
  'destinar', 'negociar', 'detectar', 'nombrar', 'acostumbrar', 'notar', 'determinar', 'activar',
  'detestar', 'numerar', 'acudir', 'devorar', 'nutrir', 'acusar', 'dibujar', 'observar', 'adaptar',
  'dictar', 'ocultar', 'adelantar', 'diferenciar', 'ocupar', 'adivinar', 'difundir', 'ocurrir',
  'adjuntar', 'dimitir', 'odiar', 'administrar', 'admirar', 'disculpar', 'olvidar', 'admitir',
  'discutir', 'omitir', 'adoptar', 'diseñar', 'operar', 'adorar', 'disfrutar', 'opinar', 'adornar',
  'disimular', 'optar', 'afectar', 'disparar', 'ordenar', 'afeitar', 'afinar',  'dividir', 'afirmar',
  'aflojar', 'oxidar', 'afrontar', 'doblar', 'parar', 'agarrar', 'dominar', 'parpadear', 'agitar',
  'donar', 'participar', 'agotar', 'dudar', 'partir', 'agradar', 'durar', 'pasar', 'aguantar', 'echar',
  'pasear', 'aguardar', 'editar', 'ahorrar', 'ejecutar', 'patear', 'ajustar', 'ejercitar', 'patinar',
  'alarmar', 'elaborar', 'pedalear', 'alborotar', 'elevar', 'peinar', 'alegrar', 'eliminar', 'pelar',
  'alejar', 'pelear', 'aligerar', 'pender', 'alimentar', 'emigrar', 'percibir', 'aliviar', 'emitir',
  'perder', 'almacenar', 'empeñar', 'perdonar', 'alojar', 'emplear', 'perfeccionar', 'alquilar',
  'emprender', 'perfumar', 'alterar', 'empujar', 'permitir', 'alumbrar', 'enamorar', 'persistir', 'amar',
  'encajar', 'persuadir', 'anhelar', 'encantar', 'pesar', 'animar', 'enchufar', 'anotar', 'encuestar',
  'pinchar', 'anticipar', 'enfadar', 'pintar', 'anular', 'enfermar', 'pisar', 'anunciar', 'enganchar',
  'planchar','añadir', 'engañar', 'planear', 'añorar', 'engordar', 'plantar', 'apartar', 'engrasar',
  'plantear', 'apelar', 'enojar', 'portar', 'aplastar', 'enredar', 'posar', 'aplaudir', 'ensanchar',
  'aportar', 'ensayar', 'preguntar', 'apoyar', 'enseñar', 'prender', 'apreciar', 'ensuciar', 'preocupar',
  'aprender', 'enterar', 'preparar', 'aprovechar', 'presentar', 'apuntar', 'entrar', 'preservar', 'apurar',
  'entrenar', 'presionar', 'arañar', 'entrevistar', 'prestar', 'entusiasmar', 'presumir', 'armar',
  'envidiar', 'pretender', 'escalar', 'arreglar', 'escapar', 'proceder', 'arrestar', 'esconder',
  'procesar', 'arrojar', 'escribir', 'proclamar', 'asar', 'escuchar', 'procurar', 'asegurar',
  'programar', 'esperar', 'progresar', 'asistir', 'prometer', 'asociar', 'estacionar', 'pronunciar',
  'asomar', 'asombrar', 'estimar', 'protestar', 'aspirar', 'estimular', 'asumir', 'estirar',
  'pulir', 'asustar', 'estornudar', 'pulsar', 'atar', 'estrenar', 'quedar', 'atrapar', 'estresar',
  'quemar', 'atrasar', 'estropear', 'quitar', 'atrever', 'estudiar', 'evadir', 'reaccionar',
  'aumentar', 'evitar', 'avisar', 'evolucionar', 'ayudar', 'exagerar', 'bailar', 'examinar',
  'recibir', 'bajar', 'excavar', 'reciclar', 'reclamar', 'bañar', 'exclamar', 'barajar',
  'barrer', 'recorrer', 'recuperar', 'batir', 'existir', 'redactar', 'beber', 'experimentar',
  'besar', 'explorar', 'reflexionar', 'bloquear', 'explotar', 'refrigerar', 'exportar',
  'regalar', 'bordar', 'expresar', 'borrar', 'exprimir', 'registrar', 'expulsar', 'regresar',
  'brindar', 'extrañar', 'regular', 'bromear', 'facilitar', 'relacionar', 'bucear', 'fallar',
  'relajar', 'burlar', 'faltar', 'relatar', 'calcular', 'rellenar', 'felicitar', 'remar',
  'callar', 'festejar', 'calmar', 'renunciar', 'cambiar', 'fijar', 'reparar', 'caminar',
  'filmar', 'repartir', 'cancelar', 'repasar', 'filtrar', 'reportar', 'financiar', 'representar',
  'cantar', 'firmar', 'resbalar', 'capturar', 'flotar', 'reservar', 'fomentar', 'resistir',
  'causar', 'formar', 'respetar', 'cautivar', 'formular', 'respirar', 'cavar', 'fracasar',
  'responder', 'ceder', 'frenar', 'restaurar', 'celebrar', 'frotar', 'resultar', 'cenar',
  'frustrar', 'resumir', 'retirar', 'centrar', 'funcionar', 'retrasar', 'cepillar', 'fundar',
  'revelar', 'fundir', 'revisar', 'charlar', 'ganar', 'rodear', 'saborear', 'gastar', 'sabotear',
  'circular', 'generar', 'saciar', 'citar', 'gestionar', 'sacudir', 'girar', 'clavar',
  'golpear', 'saltar', 'cobrar', 'grabar', 'saludar', 'cocinar', 'gritar', 'salvar', 'coincidir',
  'guardar', 'sanar', 'colaborar', 'gustar', 'seleccionar', 'coleccionar', 'habitar', 'señalar',
  'colorear', 'hablar', 'separar', 'combatir', 'hallar', 'simular', 'combinar', 'comentar',
  'hundir', 'comer', 'ignorar', 'socorrer', 'comerciar', 'iluminar', 'solicitar', 'cometer',
  'ilustrar', 'solucionar', 'comparar', 'imaginar', 'compartir', 'imitar', 'soplar', 'compensar',
  'implementar', 'soportar', 'compilar', 'importar', 'sorprender', 'completar', 'impresionar',
  'sospechar', 'comportar', 'imprimir', 'subir', 'comprar', 'improvisar', 'subrayar', 'comprender',
  'inaugurar', 'suceder', 'comprimir', 'inclinar', 'sudar', 'comprometer', 'incorporar', 'sufrir',
  'conceder', 'incrementar', 'sujetar', 'concentrar', 'informar', 'sumar', 'ingresar', 'superar',
  'condicionar', 'inhalar', 'suplir', 'conectar', 'iniciar', 'suprimir', 'configurar', 'inmigrar',
  'surtir', 'confirmar', 'insertar', 'suspender', 'confundir', 'insistir', 'suspirar', 'congelar',
  'inspeccionar', 'tapar', 'inspirar', 'tararear', 'conquistar', 'instalar', 'tardar', 'conservar',
  'insultar', 'considerar', 'integrar', 'tejer', 'intentar', 'intercambiar', 'temer', 'constatar',
  'consultar', 'interpretar', 'consumir', 'interrumpir', 'terminar', 'contactar',
  'inundar', 'contaminar', 'invadir', 'tirar', 'contemplar', 'inventar', 'contestar', 'invitar',
  'tolerar', 'contratar', 'tomar', 'controlar', 'conversar', 'juntar', 'toser', 'jurar', 'trabajar',
  'convivir', 'laborar', 'traicionar', 'cooperar', 'tramar', 'coordinar', 'lamentar', 'copiar',
  'transformar', 'lastimar', 'transmitir', 'transportar', 'correr', 'lavar', 'tratar', 'levantar',
  'cortar', 'triunfar', 'cosechar', 'liberar', 'tumbar', 'coser', 'limitar', 'unir', 'crear',
  'limpiar', 'untar', 'usar', 'cubrir', 'llamar', 'cuidar', 'llenar', 'culpar', 'llevar', 'vender',
  'cultivar', 'llorar', 'cumplir', 'viajar', 'curar', 'lograr', 'dañar', 'luchar', 'vigilar',
  'debatir', 'madurar', 'vincular', 'deber', 'decepcionar', 'visitar', 'decidir', 'declarar',
  'marchar', 'vivir', 'voltear', 'decorar', 'vomitar', 'definir', 'votar'
];

export const verbsEndings ={
  ar: ['o', 'as', 'a', 'a', 'amos', 'áis', 'an', 'an'],
  er: ['o', 'es', 'e', 'e', 'emos', 'éis', 'en', 'en'],
  ir: ['o', 'es', 'e', 'e', 'imos', 'ís', 'en', 'en'],
};

export const pronouns = ['Yo', 'Tú', 'Él', 'Ella', 'Nosotros', 'Vosotros', 'Ustedes', 'Ellos'];
